name: kitkonsult
favicon: null
layout_spectrum: 0.75367
typography_spectrum: 0.9050179
title: 'KIT Konsult - Aligning business & IT'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#044A8F'
    - '#6699C8'
    - '#667D8F'
    - '#D8E1E8'
  brandStrength: 0.5125448
  lightness: 0.4375
  saturation: 0.8188675
  rhythmicContrast: 0.7462087
purpose: []
